load("@rules_rust//rust:defs.bzl", "rust_binary")
load("@crate_index_cargo_workspace//:defs.bzl", "all_crate_deps")

rust_binary(
    name = "bin",
    srcs = [
        "src/main.rs",
    ],
    edition = "2021",
    deps = all_crate_deps(),
)
